import type{ Report } from '../types';

export const generateWhatsAppMessage = (report: Report): string => {
  const patient = report.patient;
  const abnormalCount = report.testResults.filter(r => r.isAbnormal).length;
  
  let message = `🧪 *Pathology Report*\n\n`;
  message += `👤 *Patient:* ${patient.name}\n`;
  message += `🆔 *ID:* ${patient.patientId}\n`;
  message += `📅 *Date:* ${report.date}\n`;
  message += `🔬 *Test:* ${report.testType}\n`;
  message += `📊 *Status:* ${report.status}\n\n`;
  
  if (report.status === 'Completed') {
    message += `📋 *Results Summary:*\n`;
    report.testResults.forEach(result => {
      const flag = result.isAbnormal ? (result.flag === 'high' ? '⬆️' : '⬇️') : '✅';
      message += `${flag} ${result.testName}: ${result.value} ${result.unit}\n`;
    });
    
    if (abnormalCount > 0) {
      message += `\n⚠️ ${abnormalCount} value(s) outside normal range\n`;
    }
  }
  
  message += `\n---\nGenerated by PathoReport Labs`;
  
  return message;
};

export const openWhatsApp = (report: Report): void => {
  const message = generateWhatsAppMessage(report);
  const encodedMessage = encodeURIComponent(message);
  const whatsappUrl = `https://wa.me/${report.patient.phone.replace(/\D/g, '')}?text=${encodedMessage}`;
  window.open(whatsappUrl, '_blank');
};

export const printReport = (): void => {
  window.print();
};