import type{ Report } from '../types';

export const generateWhatsAppMessage = (report: Report): string => {
  const patient = report.patient;
  const tests = report.tests || [];
  
  // Count abnormal results across all tests
  const abnormalCount = tests.reduce((count, test) => {
    return count + test.testResults.filter(r => r.isAbnormal).length;
  }, 0);

  let message = `PATHOLOGY REPORT\n\n`;
  message += `Patient Name : ${patient.name}\n`;
  message += `Patient ID   : ${patient.patientId}\n`;
  message += `Report Date  : ${report.date}\n`;
  message += `Status       : ${report.status}\n\n`;

  if (report.status === 'Completed') {
    message += `TESTS:\n`;
    
    tests.forEach((testGroup, idx) => {
      message += `\n${idx + 1}. ${testGroup.testType}\n`;
      message += `-----------------------------------\n`;

      testGroup.testResults.forEach(result => {
        let flag = 'NORMAL';
        if (result.isAbnormal) {
          flag = result.flag === 'high' ? 'HIGH' : 'LOW';
        }
        message += `- ${result.testName}: ${result.value} ${result.unit} (${flag})\n`;
      });
    });

    if (abnormalCount > 0) {
      message += `\nWARNING: ${abnormalCount} value(s) outside normal range\n`;
    }
  }

  message += `\n------------------------------\n`;
  message += `Generated by PathoReport Labs`;

  return message;
};

// Open Whatsapp and share pationt data
export const openWhatsApp = (report: Report): void => {
  const message = generateWhatsAppMessage(report);
  const encodedMessage = encodeURIComponent(message);
  const whatsappUrl = `https://wa.me/${report.patient.phone.replace(/\D/g, '')}?text=${encodedMessage}`;
  window.open(whatsappUrl, '_blank');
};

export const printReport = (): void => {
  window.print();
};